/* Project data */
const PROJECTS = [
  {
    slug: "vivobiome-carbon",
    title: "Closer to Barefoot – The VivoBiome X Carbon Innovation Story",
    label: "INNOVATION FILM · 2025",
    runtime: "",
    role: "Cinematographer · Editor",
    youtubeId: "3jcSmsDzo0g",
    blurb: "An innovation film showcasing how Vivobarefoot and Carbon are advancing personalized footwear through scan-to-print manufacturing.",
  },
  {
    slug: "powered-by-carbon",
    title: "Powered by Carbon",
    label: "BRAND FILM · 2025",
    runtime: "",
    role: "Cinematographer · Editor",
    youtubeId: "uhWU1IlGd68",
    blurb: "Anthem film launching Carbon's ingredient branding campaign and showcasing the industries, products, and innovations enabled by Carbon technology.",
  },
  {
    slug: "vicis-carbon",
    title: "VICIS x Carbon | ZERO2 MATRIX",
    label: "PARTNERSHIP FILM · 2025",
    runtime: "",
    role: "Cinematographer · Editor",
    youtubeId: "4rFWEOplTPY",
    blurb: "Partnership and innovation film showcasing how VICIS leverages Carbon's 3D printing technology to create advanced helmet liners for the ZERO2 MATRIX.",
  },
  {
    slug: "bonadent-spotlight",
    title: "Bonadent: Automatic Print Preparation",
    label: "CUSTOMER SPOTLIGHT · 2025",
    runtime: "",
    role: "Cinematographer · Co-Editor",
    youtubeId: "d2Twe5qKpP8",
    blurb: "Customer spotlight on Bonadent Dental Lab, highlighting how Carbon's Automatic Print Preparation software is streamlining their dental lab's production workflow.",
  },
  {
    slug: "climacool-laced",
    title: "Climacool Laced",
    label: "BRAND FILM · 2025",
    runtime: "",
    role: "Director · Cinematographer · Editor",
    youtubeId: "gGOyLY9OUko",
    blurb: "Fast-paced social media spot celebrating the latest colorway of the adidas Climacool Laced shoe.",
  },
  {
    slug: "running-cycle-tester",
    title: "Running Cycle Tester: Carbon Materials Under Extreme Testing",
    label: "INNOVATION FILM · 2025",
    runtime: "",
    role: "Cinematographer · Editor",
    youtubeId: "c16W8Dh68EI",
    blurb: "A look inside the running cycle test used to evaluate the durability of Carbon materials under repeated loading.",
  },
  {
    slug: "hiit-school",
    title: "HIIT School",
    label: "BRAND FILM · 2025",
    runtime: "",
    role: "Director · Cinematographer · Editor",
    youtubeId: "KawqXQfp660",
    blurb: "Brand showcase reel for HIIT School highlighting their high-intensity class offerings.",
  },
  {
    slug: "ballet-academy-sv",
    title: "Ballet Academy of Silicon Valley",
    label: "BRAND FILM · 2025",
    runtime: "",
    role: "Director · Cinematographer · Editor",
    youtubeId: "yLVfBQp6ang",
    blurb: "Brand film for Ballet Academy of Silicon Valley showcasing their programs and artistic vision.",
  },
  {
    slug: "riddell-axiom-3d",
    title: "Riddell Axiom 3D",
    label: "HYPE REEL · 2025",
    runtime: "",
    role: "Director · Cinematographer · Editor · Motion Graphics",
    youtubeId: "n9uWk9HFiMk",
    blurb: "Hype reel for the Riddell Axiom 3D launch, promoted across Carbon social channels for the Helmets Powered by Carbon campaign.",
  },
  {
    slug: "rosalind-bakery",
    title: "Rosalind Bakery",
    label: "BRAND FILM · 2026",
    runtime: "",
    role: "Director · Cinematographer · Editor",
    youtubeId: "Aa3ApH57bec",
    blurb: "A look inside Rosalind Bakery in Pacifica, California, where a signature croissant is made from scratch with precision, patience, and tradition.",
  },
  {
    slug: "grant-koniski-fluid-artist",
    title: "Fluid Artist & Skateboarder: Grant Koniski",
    label: "PROFILE FILM · 2026",
    runtime: "",
    role: "Director · Cinematographer · Editor",
    youtubeId: "bS1ICEyvm6Y",
    blurb: "Grant Koniski explores emotion and the human psyche through fluid acrylics, instinct, and controlled chaos. From building each canvas by hand to the final pour, his process is deeply personal and entirely one of a kind. This film offers a glimpse into the mindset and craftsmanship behind his work.",
  },
  {
    slug: "ovial-surgical-nutrition",
    title: "Ovial Surgical Nutrition",
    label: "PRODUCT FILM · 2026",
    runtime: "",
    role: "Director · Cinematographer · Editor",
    youtubeId: "U65WrruneLg",
    blurb: "OVIAL needed a visual asset for its website that showcased both the product and how it fits into the surgical recovery process. The film highlights OVIAL's surgeon-formulated nutrition system through clean product imagery and real-world use, reinforcing its role in supporting the body before and after surgery.",
  },
];

window.PROJECTS = PROJECTS;
